[workspace]
authors = ["JHIH-SIOU LI <jsli@linux.com>"]
channels = ["conda-forge"]
name = "dl-exp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
cuda = "12.6.0.*"
cudnn = ">=9.10.1.4,<10"
cmake = ">=4.0.2,<5"
ninja = ">=1.12.1,<2"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
torch = { version = "==2.6.0", index = "https://download.pytorch.org/whl/cu126" }
torchvision = { version = "==0.21.0", index = "https://download.pytorch.org/whl/cu126" }
torchaudio = { version = "==2.6.0", index = "https://download.pytorch.org/whl/cu126" }
kaggle = ">=1.7.4.5, <2"
polars = ">=1.30.0, <2"
mkl-static = ">=2025.1.0, <2026"
mkl-include = ">=2025.1.0, <2026"
