[workspace]
authors = ["JHIH-SIOU LI <jsli@linux.com>"]
channels = ["conda-forge"]
name = "dl-exp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
cuda = "12.8.0.*"

[pypi-dependencies]
torch = {  index = "https://download.pytorch.org/whl/cu128" }
torchvision = {  index = "https://download.pytorch.org/whl/cu128" }
kaggle = ">=1.7.4.5, <2"
